#
# Copyright 2013-2015, Bromium, Inc.
# SPDX-License-Identifier: ISC
#

BUILDDIR_default = obj
SRCDIR ?= .
TOPDIR = $(abspath $(SRCDIR)/../..)
include $(TOPDIR)/Config.mk

ifeq (,$(MAKENOW))

SRCROOT = $(abspath $(TOPDIR)/dm)

VPATH = $(SRCROOT)

YAJLDIR = $(call builddir,../yajl)/install

include $(SRCROOT)/Makefile.libimg

endif # MAKENOW
