/* Inlined in perfcnt.c and perfcnt.h */

PERFCNT(DxgkDdiAddDevice)
PERFCNT(DxgkDdiStartDevice)
PERFCNT(DxgkDdiStopDevice)
PERFCNT(DxgkDdiResetDevice)
PERFCNT(DxgkDdiRemoveDevice)
PERFCNT(DxgkDdiDispatchIoRequest)
PERFCNT(DxgkDdiInterruptRoutine)
PERFCNT(DxgkDdiDpcRoutine)
PERFCNT(DxgkDdiQueryChildRelations)
PERFCNT(DxgkDdiQueryChildStatus)
PERFCNT(DxgkDdiQueryDeviceDescriptor)
PERFCNT(DxgkDdiSetPowerState)
PERFCNT(DxgkDdiUnload)
PERFCNT(DxgkDdiQueryAdapterInfo)
PERFCNT(DxgkDdiSetPointerPosition)
PERFCNT(DxgkDdiSetPointerShape)
PERFCNT(DxgkDdiIsSupportedVidPn)
PERFCNT(DxgkDdiRecommendFunctionalVidPn)
PERFCNT(DxgkDdiEnumVidPnCofuncModality)
PERFCNT(DxgkDdiSetVidPnSourceVisibility)
PERFCNT(DxgkDdiCommitVidPn)
PERFCNT(DxgkDdiUpdateActiveVidPnPresentPath)
PERFCNT(DxgkDdiRecommendMonitorModes)
PERFCNT(DxgkDdiQueryVidPnHWCapability)
PERFCNT(DxgkDdiPresentDisplayOnly)
PERFCNT(DxgkDdiStopDeviceAndReleasePostDisplayOwnership)
PERFCNT(DxgkDdiSystemDisplayEnable)
PERFCNT(DxgkDdiSystemDisplayWrite)
PERFCNT(DxgkDdiRecommendVidPnTopology)
PERFCNT(DxgkDdiEscape)

PERFCNT(BlackOutScreen)
PERFCNT(SetNextMode)
PERFCNT(hw_set_mode)
