/*
Bromium Inc

Module Name:  Event.h

Declare the Generic format for events.
*/
/*
 * Copyright 2013-2015, Bromium, Inc.
 * SPDX-License-Identifier: ISC
 */

#ifndef __BRO_EVENT_H__
#define __BRO_EVENT_H__

#define BRO_EVENT_TYPE_START           0x00000000

#define BRO_SYS_EVENT_TYPE_START       0x00000000
#define BRO_SYS_EVENT_TYPE_END         0x0000FFFF

#define BRO_FILE_EVENT_TYPE_START      0x00010000
#define BRO_FILE_EVENT_TYPE_END        0x0001FFFF

#define BRO_REG_EVENT_TYPE_START       0x00020000
#define BRO_REG_EVENT_TYPE_END         0x0002FFFF

#define BRO_PROC_EVENT_TYPE_START      0x00030000
#define BRO_PROC_EVENT_TYPE_END        0x0003FFFF

#define BRO_INTRO_EVENT_TYPE_START     0x00040000
#define BRO_INTRO_EVENT_TYPE_END       0x0004FFFF

#define BRO_NETWORK_EVENT_TYPE_START   0x00050000
#define BRO_NETWORK_EVENT_TYPE_END     0x0005FFFF

#define BRO_HOOK_EVENT_TYPE_START	   0x00060000
#define BRO_HOOK_EVENT_TYPE_LAST	   0x0006FFFF

#define BRO_EVENT_TYPE_END             0x0006FFFF

#define VALID_SYS_EVENT(x)     (((x) >= BRO_SYS_EVENT_TYPE_START)   && ((x) < BRO_EVENT_TYPE_SYS_LAST))
#define VALID_FSMON_EVENT(x)   (((x) >= BRO_FILE_EVENT_TYPE_START)  && ((x) < BRO_EVENT_TYPE_FILE_LAST))
#define VALID_REGMON_EVENT(x)  (((x) >= BRO_REG_EVENT_TYPE_START)   && ((x) < BRO_EVENT_TYPE_REG_LAST))
#define VALID_PROCMON_EVENT(x) (((x) >= BRO_PROC_EVENT_TYPE_START)  && ((x) < BRO_EVENT_TYPE_PROC_LAST))
#define VALID_INTROSP_EVENT(x) (((x) >= BRO_INTRO_EVENT_TYPE_START) && ((x) < BRO_EVENT_TYPE_INTRO_LAST))
#define VALID_NETWORK_EVENT(x) (((x) >= BRO_NETWORK_EVENT_TYPE_START) && ((x) < BRO_EVENT_TYPE_NETWORK_LAST))
#define VALID_HOOK_EVENT(x) (((x) >= BRO_HOOK_EVENT_TYPE_START) && ((x) < BRO_HOOK_EVENT_TYPE_LAST))

typedef enum _BRO_EVENT_TYPE{
		/* System Event Types */
		BRO_EVENT_TYPE_UNKNOWN = BRO_SYS_EVENT_TYPE_START,       /* 0x00000000 */
		BRO_EVENT_TYPE_SYS_PROCINVOCATION_THRESHOLD,
		BRO_EVENT_TYPE_SYS_FILEHASH,
		BRO_EVENT_TYPE_SYS_LAST,

		/* File Event Types */
		BRO_EVENT_TYPE_FILE_WRITE  = BRO_FILE_EVENT_TYPE_START,      /* 0x00010000 */
		BRO_EVENT_TYPE_FILE_DELETE,
		BRO_EVENT_TYPE_FILE_DIR_DELETE,
		BRO_EVENT_TYPE_FILE_HARDLINK_FILE,
		BRO_EVENT_TYPE_FILE_RENAME,
		BRO_EVENT_TYPE_FILE_DIR_RENAME,
		BRO_EVENT_TYPE_FILE_HIDE,
		BRO_EVENT_TYPE_FILE_TIMESTAMP_CHANGE,
		BRO_EVENT_TYPE_FILE_LAST,

		/* Reg Event Types */
		BRO_EVENT_TYPE_REG_DELETE_KEY = BRO_REG_EVENT_TYPE_START,    /* 0x00020000 */
		BRO_EVENT_TYPE_REG_SETVALUE,
		BRO_EVENT_TYPE_REG_DELETEVALUE,
		BRO_EVENT_TYPE_REG_RENAME_KEY,
		BRO_EVENT_TYPE_REG_CREATE_KEY,
		BRO_EVENT_TYPE_REG_LAST,

		/* Process Event Types */
		BRO_EVENT_TYPE_PROC_CREATE = BRO_PROC_EVENT_TYPE_START,      /* 0x00030000 */
		BRO_EVENT_TYPE_PROC_MAP,
		BRO_EVENT_TYPE_PROC_TERMINATE,
		BRO_EVENT_TYPE_PROC_LOADIMAGE,
		BRO_EVENT_TYPE_PROC_LOADIMAGE_SYS,
		BRO_EVENT_TYPE_PROC_OPENPROCESS,
		BRO_EVENT_TYPE_PROC_LAST,
		
		/* Introspection Event Types */
		BRO_EVENT_TYPE_INTRO_BOOT_SECTOR_WRITE= BRO_INTRO_EVENT_TYPE_START,
		BRO_EVENT_TYPE_INTRO_WP_CR0_CLEAR,
		BRO_EVENT_TYPE_INTRO_VMXE_CR4_SET,
        BRO_EVENT_TYPE_INTRO_IMMUTABLE_MEMORY_VIOLATION,
        BRO_EVENT_TYPE_INTRO_HIDDEN_PROCESS_DETECTED,
        BRO_EVENT_TYPE_INTRO_DEBUG_ROOTKIT,
        BRO_EVENT_TYPE_INTRO_CALLBACKS_COMPROMISED,
        BRO_EVENT_TYPE_INTRO_SMEP_VIOLATION,
        BRO_EVENT_TYPE_INTRO_SMEP_CR4_CLEAR,
		BRO_EVENT_TYPE_INTRO_LAST,
		
		/* Network Event Types */
		BRO_EVENT_TYPE_NETWORK_IP_ACL= BRO_NETWORK_EVENT_TYPE_START,
		BRO_EVENT_TYPE_NETWORK_DNS_ACL,
        BRO_EVENT_TYPE_GUEST_TCPUDP_CONNECT,
        BRO_EVENT_TYPE_GUEST_ICMP_CONNECT,
        BRO_EVENT_TYPE_GUEST_TCP_LISTEN,
		BRO_EVENT_TYPE_NETWORK_LAST,
		
		/* Hook Event Types */
		BRO_EVENT_TYPE_HOOK= BRO_HOOK_EVENT_TYPE_START,               /* 0x00060000 */
		BRO_EVENT_TYPE_HOOK_LAST,
		
		/* Last Event type */
		BRO_EVENT_TYPE_LAST = BRO_EVENT_TYPE_END,

}BRO_EVENT_TYPE;

#endif

