
#ifndef _QEMU_QUEUE_H_
#define _QEMU_QUEUE_H_

#include "queue.h"
#define QLIST_FIRST LIST_FIRST
#define QLIST_HEAD LIST_HEAD
#define QLIST_HEAD_INITIALIZER LIST_HEAD_INITIALIZER
#define QLIST_INIT LIST_INIT
#define QLIST_INSERT_HEAD LIST_INSERT_HEAD
#define QLIST_ENTRY LIST_ENTRY
#define QLIST_FOREACH LIST_FOREACH
#define QLIST_FOREACH_SAFE LIST_FOREACH_SAFE
#define QLIST_REMOVE LIST_REMOVE
#define QTAILQ_EMPTY TAILQ_EMPTY
#define QTAILQ_ENTRY TAILQ_ENTRY
#define QTAILQ_FIRST TAILQ_FIRST
#define QTAILQ_FOREACH TAILQ_FOREACH
#define QTAILQ_FOREACH_SAFE TAILQ_FOREACH_SAFE
#define QTAILQ_HEAD TAILQ_HEAD
#define QTAILQ_HEAD_INITIALIZER TAILQ_HEAD_INITIALIZER
#define QTAILQ_INIT TAILQ_INIT
#define QTAILQ_INSERT_HEAD TAILQ_INSERT_HEAD
#define QTAILQ_INSERT_TAIL TAILQ_INSERT_TAIL
#define QTAILQ_REMOVE TAILQ_REMOVE
#define QTAILQ_FOREACH_REVERSE TAILQ_FOREACH_REVERSE

#endif	/* _QEMU_QUEUE_H_ */
