
UXEN_TOOLS_TARGETS ?= $(TARGET_HOST)

BUILD_WINDOWS_TOOLS := $(if $(filter windows,$(UXEN_TOOLS_TARGETS)),,n-)
BUILD_OSX_TOOLS := $(if $(filter osx,$(UXEN_TOOLS_TARGETS)),,n-)

CROSS_MINGW_INSTALL_DIR = $(TOOLSDIR)/cross-mingw
CROSS_OSX_INSTALL_DIR = $(TOOLSDIR)/cross-osx
CROSS_VM_INSTALL_DIR = $(TOOLSDIR)/cross-vm
CROSS_W64L_INSTALL_DIR = $(TOOLSDIR)/cross-w64l
CROSS_WINDOWS_INSTALL_DIR = $(TOOLSDIR)/cross-windows

HOST_ALL_INSTALL_DIR = $(TOOLSDIR)/host-all
HOST_ALL_32_INSTALL_DIR = $(TOOLSDIR)/host-all-32
HOST_LINUX_INSTALL_DIR = $(TOOLSDIR)/host-linux
HOST_OSX_INSTALL_DIR = $(TOOLSDIR)/host-osx
HOST_WINDOWS_INSTALL_DIR = $(TOOLSDIR)/host-windows

XEN_DISTFILES ?= $(TOPDIR)/../distfiles

BUILD_ENV += CPPFLAGS="$$CPPFLAGS -g"
BUILD_ENV += LDFLAGS="$$LDFLAGS -g"
BUILD_ENV32 += CPPFLAGS="$$CPPFLAGS -g"
BUILD_ENV32 += LDFLAGS="$$LDFLAGS -g"
